### PR TITLE
Update prompt-toolkit to 1.0.15

### PR DESCRIPTION
**Pull request by danodonovan**
I'm noticing that `prompt-toolkit==0.57` breaks my `ipython==5.3.0` installation (for python 3 at least). Bumping the `prompt-toolkit` version fixes this, the tests run and `cycli` seems to work as expected.

PS Thanks for the great tool 👍

### CODE REVIEW

**Comment by danodonovan** [comment]
Should `neokit` submodule and invocation updates be in a separate pull request?

**Comment by danodonovan** [comment]
I've made a couple of separate PRs addressing a couple of issues I spotted. Bit puzzled how the tests were passing [I would have expected them to fail before #57] , but I can run and use locally.

**Comment by nicolewhite** [comment]
I think the tests are not being run at all. There is no output on Travis.

**Comment by nicolewhite** [comment]
Can you separate the update to prompt toolkit into its own PR?

**Pull request merged**
