### PR TITLE
Upgrade to prompt_toolkit 0.57

### PR DESCRIPTION
**Pull request by jonathanslenders**
Changes required for the latest prompt_toolkit.
Many thing have been improved and bugs have been fixed.
(E.g. mouse support, pasting of multiline text, 

Have a look at the changelog: https://github.com/jonathanslenders/python-prompt-toolkit/blob/master/CHANGELOG

Feel free to not merge it if it doesn't work for you. I didn't do any extensive testing.
Jonathan

### CODE REVIEW

**Comment by nicolewhite** [comment]
Thanks @jonathanslenders, I'll try to get the tests passing.

**Comment by jonathanslenders** [comment]
I guess it should be fine after adding ``from __future__ import unicode_literals`` at the start of ``cycly/binder.py``.

**Comment by nicolewhite** [comment]
Yeah that's what it looks like. I'll get to it soon. :+1:

**Comment by nicolewhite** [comment]
This was merged in https://github.com/nicolewhite/cycli/commit/2221735f4cfceb602f22265ded4feab68bcd8f5b. Not sure why this wasn't closed automatically.

**Pull request closed without merging**
